import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 16,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    headerText: {
      flex: 1,
    },
    eyebrow: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 3,
    },
    title: {
      fontSize: 23,
      fontWeight: "900",
      color: theme.colors.text,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 46,
    },
    heroPanel: {
      backgroundColor: theme.colors.card,
      borderRadius: 26,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 16,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 18,
      elevation: isDarkMode ? 0 : 3,
    },
    heroIcon: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.primary + "20",
    },
    heroTitle: {
      color: theme.colors.text,
      fontSize: 24,
      fontWeight: "900",
      lineHeight: 30,
      marginBottom: 8,
    },
    heroSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 21,
    },
    heroStats: {
      flexDirection: "row",
      gap: 10,
      marginTop: 16,
    },
    heroStat: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F8FAFC",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    heroStatText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: "800",
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 18,
      paddingHorizontal: 16,
      height: 56,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    searchInput: {
      flex: 1,
      marginLeft: 12,
      fontSize: 15,
      color: theme.colors.text,
      fontWeight: "600",
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "900",
      color: theme.colors.text,
      marginBottom: 12,
    },
    sectionSubtitle: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    productItem: {
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    productLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      minWidth: 0,
    },
    productIcon: {
      width: 50,
      height: 50,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
      overflow: "hidden",
      backgroundColor: theme.colors.primary + "12",
    },
    productImage: {
      width: "100%",
      height: "100%",
    },
    productInfo: {
      flex: 1,
      minWidth: 0,
    },
    productName: {
      fontSize: 15,
      fontWeight: "900",
      color: theme.colors.text,
      marginBottom: 5,
    },
    productMeta: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
    },
    chevronWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F8FAFC",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginLeft: 10,
    },
    changeButton: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      paddingHorizontal: 13,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: theme.colors.primary + "12",
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
      marginBottom: 16,
    },
    changeButtonText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: "900",
    },
    scoreCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 28,
      padding: 22,
      alignItems: "center",
      marginBottom: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDarkMode ? 0 : 0.08,
      shadowRadius: 22,
      elevation: isDarkMode ? 0 : 5,
    },
    scoreRing: {
      width: 126,
      height: 126,
      borderRadius: 63,
      borderWidth: 9,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
      backgroundColor: theme.colors.background,
    },
    scoreValue: {
      fontSize: 39,
      fontWeight: "900",
      lineHeight: 43,
    },
    scoreMax: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      fontWeight: "900",
    },
    scoreProduct: {
      fontSize: 22,
      fontWeight: "900",
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: 10,
    },
    scoreBadge: {
      paddingHorizontal: 13,
      paddingVertical: 7,
      borderRadius: 999,
    },
    scoreBadgeText: {
      fontSize: 12,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    insightCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      gap: 13,
    },
    benefitItem: {
      flexDirection: "row",
      alignItems: "flex-start",
    },
    benefitIcon: {
      width: 32,
      height: 32,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 11,
    },
    benefitText: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.text,
      lineHeight: 21,
      fontWeight: "600",
      paddingTop: 4,
    },
    tipBox: {
      backgroundColor: theme.colors.primary + "10",
      padding: 18,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.primary + "30",
    },
    tipTitle: {
      fontSize: 12,
      fontWeight: "900",
      color: theme.colors.primary,
      textTransform: "uppercase",
      marginBottom: 8,
      letterSpacing: 0.5,
    },
    tipContent: {
      fontSize: 15,
      color: theme.colors.text,
      lineHeight: 23,
      fontWeight: "700",
    },
    loadingContainer: {
      height: 280,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingText: {
      marginTop: 16,
      fontSize: 14,
      color: theme.colors.textSecondary,
      fontWeight: "700",
    },
  });
