import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 20,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 16,
      paddingHorizontal: 16,
      height: 56,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    searchInput: {
      flex: 1,
      marginLeft: 12,
      fontSize: 16,
      color: theme.colors.text,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: 16,
    },
    productItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    productIcon: {
      width: 48,
      height: 48,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
      overflow: "hidden",
    },
    productName: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.text,
      flex: 1,
    },
    scoreCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 24,
      alignItems: "center",
      marginBottom: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
    },
    scoreCircle: {
      width: 120,
      height: 120,
      borderRadius: 60,
      borderWidth: 8,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    scoreValue: {
      fontSize: 32,
      fontWeight: "bold",
    },
    scoreLabel: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      fontWeight: "600",
    },
    insightCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    benefitItem: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 12,
    },
    benefitDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginTop: 6,
      marginRight: 12,
    },
    benefitText: {
      flex: 1,
      fontSize: 15,
      color: theme.colors.text,
      lineHeight: 22,
    },
    tipBox: {
      backgroundColor: theme.colors.primary + "10",
      padding: 20,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.primary + "30",
    },
    tipTitle: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.primary,
      textTransform: "uppercase",
      marginBottom: 8,
      letterSpacing: 1,
    },
    tipContent: {
      fontSize: 16,
      color: theme.colors.text,
      lineHeight: 24,
      fontWeight: "500",
    },
    loadingContainer: {
      height: 300,
      justifyContent: "center",
      alignItems: "center",
    },
  });
