import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 20,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.colors.text,
      marginTop: 20,
      marginBottom: 16,
    },
    ingredientItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 16,
      marginBottom: 10,
      borderWidth: 1,
    },
    recipeCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 24,
      marginTop: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 10,
    },
    recipeTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 12,
      textAlign: "center",
    },
    recipeMeta: {
      flexDirection: "row",
      justifyContent: "center",
      marginBottom: 20,
      gap: 16,
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.primary + "10",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
    },
    metaText: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.primary,
      marginLeft: 6,
    },
    ingredientList: {
      marginBottom: 24,
    },
    instructionStep: {
      flexDirection: "row",
      marginBottom: 16,
    },
    stepNumber: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
      marginTop: 2,
    },
    stepNumberText: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "bold",
    },
    stepText: {
      flex: 1,
      fontSize: 15,
      color: theme.colors.text,
      lineHeight: 22,
    },
    wasteTip: {
      backgroundColor: "#FFFBEB",
      padding: 16,
      borderRadius: 16,
      marginTop: 20,
      borderWidth: 1,
      borderColor: "#FDE68A",
    },
    wasteTipTitle: {
      color: "#D97706",
      fontWeight: "800",
      fontSize: 12,
      marginBottom: 4,
      textTransform: "uppercase",
    },
    wasteTipText: {
      color: "#92400E",
      fontSize: 14,
      fontStyle: "italic",
    },
    generateButton: {
      height: 56,
      backgroundColor: theme.colors.primary,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 24,
      flexDirection: "row",
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    generateButtonText: {
      color: "#FFF",
      fontSize: 18,
      fontWeight: "bold",
      marginLeft: 10,
    },
  });
