import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 16,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    headerText: {
      flex: 1,
    },
    eyebrow: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 3,
    },
    title: {
      fontSize: 23,
      fontWeight: "900",
      color: theme.colors.text,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 46,
    },
    heroPanel: {
      backgroundColor: theme.colors.card,
      borderRadius: 26,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 18,
      elevation: isDarkMode ? 0 : 3,
    },
    heroIcon: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.primary + "20",
    },
    heroTitle: {
      color: theme.colors.text,
      fontSize: 24,
      fontWeight: "900",
      lineHeight: 30,
      marginBottom: 8,
    },
    heroSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 21,
    },
    heroStats: {
      flexDirection: "row",
      gap: 10,
      marginTop: 16,
    },
    heroStat: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F8FAFC",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    heroStatText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: "800",
    },
    selectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 24,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "900",
      color: theme.colors.text,
      marginBottom: 5,
    },
    sectionSubtitle: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
    },
    clearButton: {
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: theme.colors.primary + "12",
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
    },
    clearButtonText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: "900",
    },
    productList: {
      gap: 10,
    },
    productItem: {
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    productItemSelected: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary + "10",
    },
    productLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      minWidth: 0,
    },
    productImageWrap: {
      width: 48,
      height: 48,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.colors.primary + "12",
      marginRight: 12,
      overflow: "hidden",
    },
    productImage: {
      width: "100%",
      height: "100%",
    },
    productInfo: {
      flex: 1,
      minWidth: 0,
    },
    productName: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: "900",
      marginBottom: 5,
    },
    productMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    productMeta: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: "700",
    },
    checkCircle: {
      width: 26,
      height: 26,
      borderRadius: 13,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.background,
      marginLeft: 10,
    },
    checkCircleActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    emptyCard: {
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 22,
      padding: 22,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    emptyTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "900",
      marginTop: 10,
      marginBottom: 6,
    },
    emptyText: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 20,
      textAlign: "center",
    },
    loadingText: {
      textAlign: "center",
      marginTop: 12,
      color: theme.colors.textSecondary,
      fontWeight: "700",
    },
    recipeCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 28,
      padding: 22,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: isDarkMode ? 0 : 0.08,
      shadowRadius: 22,
      elevation: isDarkMode ? 0 : 5,
    },
    recipeHeroIcon: {
      width: 62,
      height: 62,
      borderRadius: 22,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
    },
    recipeTitle: {
      fontSize: 23,
      fontWeight: "900",
      color: theme.colors.text,
      marginBottom: 14,
      textAlign: "center",
      lineHeight: 29,
    },
    recipeMeta: {
      flexDirection: "row",
      justifyContent: "center",
      marginBottom: 24,
      gap: 12,
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.primary + "10",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.primary + "18",
    },
    metaText: {
      fontSize: 12,
      fontWeight: "900",
      color: theme.colors.primary,
      marginLeft: 6,
    },
    ingredientList: {
      marginBottom: 20,
      gap: 9,
    },
    recipeIngredientRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    recipeIngredientDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginRight: 10,
    },
    recipeIngredientText: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
    },
    instructionStep: {
      flexDirection: "row",
      marginBottom: 15,
    },
    stepNumber: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
      marginTop: 1,
    },
    stepNumberText: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "900",
    },
    stepText: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.text,
      lineHeight: 22,
      fontWeight: "600",
    },
    wasteTip: {
      backgroundColor: "#FFFBEB",
      padding: 16,
      borderRadius: 18,
      marginTop: 12,
      borderWidth: 1,
      borderColor: "#FDE68A",
    },
    wasteTipTitle: {
      color: "#D97706",
      fontWeight: "900",
      fontSize: 12,
      marginBottom: 6,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    wasteTipText: {
      color: "#92400E",
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "600",
    },
    editIngredientsButton: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      paddingHorizontal: 13,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: theme.colors.primary + "12",
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
      marginBottom: 16,
    },
    editIngredientsText: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: "900",
    },
    generateButton: {
      minHeight: 56,
      backgroundColor: theme.colors.primary,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 24,
      flexDirection: "row",
      paddingHorizontal: 18,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: isDarkMode ? 0 : 0.22,
      shadowRadius: 10,
      elevation: isDarkMode ? 0 : 4,
    },
    generateButtonText: {
      color: "#FFF",
      fontSize: 17,
      fontWeight: "900",
      marginLeft: 9,
    },
    secondaryButton: {
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "transparent",
    },
    secondaryText: {
      color: theme.colors.text,
      marginLeft: 0,
    },
  });
