import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 58,
      paddingBottom: 120,
    },
    heroCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 30,
      padding: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDarkMode ? 0.1 : 0.07,
      shadowRadius: 22,
      elevation: 4,
    },
    heroTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    heroBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: theme.colors.primary + "12",
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
    },
    heroBadgeText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: "900",
    },
    heroIcon: {
      width: 46,
      height: 46,
      borderRadius: 17,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.primary + "24",
    },
    greeting: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      fontWeight: "900",
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 6,
    },
    title: {
      fontSize: 31,
      fontWeight: "900",
      color: theme.colors.text,
      letterSpacing: -0.5,
      lineHeight: 37,
    },
    subtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      lineHeight: 21,
      fontWeight: "600",
      marginTop: 10,
    },
    featuredCard: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.colors.secondary,
      borderRadius: 12,
      padding: 18,
      marginBottom: 22,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.22,
      shadowRadius: 18,
      elevation: 5,
    },
    featuredContent: {
      flex: 1,
      paddingRight: 14,
    },
    featuredBadge: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: "rgba(255,255,255,0.18)",
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginBottom: 14,
    },
    featuredBadgeText: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "900",
    },
    featuredTitle: {
      color: "#FFFFFF",
      fontSize: 22,
      fontWeight: "900",
      lineHeight: 27,
      marginBottom: 6,
    },
    featuredDesc: {
      color: "rgba(255,255,255,0.82)",
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 19,
    },
    featuredIcon: {
      width: 62,
      height: 62,
      borderRadius: 22,
      backgroundColor: "rgba(255,255,255,0.18)",
      justifyContent: "center",
      alignItems: "center",
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 19,
      fontWeight: "900",
      color: theme.colors.text,
    },
    sectionSubtitle: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    card: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 14,
      marginBottom: 12,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: isDarkMode ? 0 : 0.04,
      shadowRadius: 14,
      elevation: isDarkMode ? 0 : 2,
    },
    iconBg: {
      width: 58,
      height: 58,
      borderRadius: 19,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 13,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    cardContent: {
      flex: 1,
      minWidth: 0,
    },
    cardTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    cardTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: "900",
      color: theme.colors.text,
    },
    cardDesc: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      lineHeight: 19,
      fontWeight: "600",
      marginBottom: 8,
    },
    cardMeta: {
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
    },
    badgeText: {
      fontSize: 9,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    chevronWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#EFF7F2",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginLeft: 10,
    },
  });
