import { StyleSheet, Dimensions } from "react-native";
import { ThemeType } from "../../constants/theme";

const { width } = Dimensions.get("window");

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    topSection: {
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      paddingTop: 46,
      paddingHorizontal: 20,
      paddingBottom: 16,
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.colors.border,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 16,
      zIndex: 10,
    },
    iconButton: {
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 10,
      elevation: isDarkMode ? 0 : 2,
    },
    deleteButton: {
      backgroundColor: isDarkMode ? "#450A0A" : "#FEF2F2",
      marginLeft: 12,
      borderColor: isDarkMode ? "#7F1D1D" : "#FECACA",
    },
    imageContainer: {
      width: "100%",
      height: 340,
      backgroundColor: theme.colors.card,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 2,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: "hidden",
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: isDarkMode ? 0.14 : 0.1,
      shadowRadius: 24,
      elevation: 8,
    },
    heroImage: {
      width: "100%",
      height: "100%",
      borderRadius: 29,
      alignSelf: "center",
    },
    titleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 4,
      marginBottom: 16,
      gap: 12,
    },
    title: {
      fontSize: 22,
      fontWeight: "800",
      color: theme.colors.text,
      flex: 1,
      letterSpacing: -0.4,
    },
    statusBadge: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 999,
    },
    statusText: {
      fontSize: 12,
      fontWeight: "900",
      color: "#FFFFFF",
      letterSpacing: 0.7,
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 18,

    },
    countdownCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 26,
      padding: 18,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 18,
      elevation: isDarkMode ? 0 : 2,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
      marginBottom: 16,
    },
    cardTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flex: 1,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: "800",
      color: theme.colors.text,
    },
    countdownValue: {
      fontSize: 22,
      fontWeight: "900",
      textAlign: "right",
    },
    progressBarBg: {
      height: 10,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.07)" : "#EFF7F2",
      borderRadius: 999,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 999,
    },
    countdownFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      marginTop: 12,
    },
    countdownHint: {
      flex: 1,
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
      lineHeight: 17,
    },
    countdownDate: {
      fontSize: 12,
      fontWeight: "900",
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    gridItem: {
      width: (width - 52) / 2,
      backgroundColor: theme.colors.card,
      borderRadius: 22,
      padding: 15,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: isDarkMode ? 0 : 0.04,
      shadowRadius: 12,
      elevation: isDarkMode ? 0 : 1,
    },
    gridIconBox: {
      width: 38,
      height: 38,
      borderRadius: 14,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "#EFF7F2",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    gridLabel: {
      fontSize: 11,
      color: theme.colors.textSecondary,
      marginBottom: 5,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    gridValue: {
      fontSize: 14,
      fontWeight: "900",
      color: theme.colors.text,
      lineHeight: 18,
    },
    notesCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 18,
      marginTop: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 16,
    },
    ingredientsCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 18,
      marginTop: 14,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    historyCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 18,
      marginTop: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 60,
    },
    historyItem: {
      flexDirection: "row",
      marginTop: 12,
      minHeight: 50,
    },
    historyLeft: {
      alignItems: "center",
      marginRight: 12,
      width: 16,
    },
    historyDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginTop: 6,
    },
    historyLine: {
      width: 2,
      flex: 1,
      backgroundColor: theme.colors.border,
      marginTop: 4,
      marginBottom: -12,
    },
    historyRight: {
      flex: 1,
      paddingBottom: 12,
    },
    historyHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 4,
    },
    historyAction: {
      fontSize: 14,
      fontWeight: "800",
      color: theme.colors.text,
    },
    historyDate: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.colors.textSecondary,
    },
    historyNote: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      fontWeight: "600",
      marginTop: 2,
      fontStyle: "italic",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(15, 23, 42, 0.6)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      backgroundColor: theme.colors.card,
      borderRadius: 28,
      padding: 22,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.25,
      shadowRadius: 18,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "900",
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: 16,
    },
    optionsList: {
      gap: 10,
      marginBottom: 16,
    },
    optionCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: 14,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      gap: 12,
    },
    optionCardSelected: {
      backgroundColor: theme.colors.primary + "0c",
      borderColor: theme.colors.primary,
    },
    optionIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    optionTextWrap: {
      flex: 1,
    },
    optionLabel: {
      fontSize: 14,
      fontWeight: "900",
      color: theme.colors.text,
    },
    optionDesc: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      fontWeight: "600",
      marginTop: 2,
    },
    qtySelectorTitle: {
      fontSize: 13,
      fontWeight: "800",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 8,
    },
    qtySelectorRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.04)" : "#F1F5F9",
      borderRadius: 16,
      padding: 6,
      marginBottom: 16,
    },
    qtyInput: {
      fontSize: 18,
      fontWeight: "900",
      color: theme.colors.text,
      textAlign: "center",
      flex: 1,
    },
    qtyBtn: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    noteInputWrapper: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 16,
      backgroundColor: isDarkMode ? "rgba(0,0,0,0.15)" : "#F8FAFC",
      paddingHorizontal: 14,
      paddingVertical: 10,
      minHeight: 64,
      marginBottom: 20,
    },
    noteTextInput: {
      fontSize: 14,
      color: theme.colors.text,
      fontWeight: "600",
      textAlignVertical: "top",
    },
    modalActions: {
      flexDirection: "row",
      gap: 12,
    },
    modalCancelBtn: {
      flex: 1,
      height: 52,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    modalCancelBtnText: {
      fontSize: 15,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    modalConfirmBtn: {
      flex: 2,
      height: 52,
      backgroundColor: theme.colors.primary,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    modalConfirmBtnText: {
      fontSize: 15,
      fontWeight: "900",
      color: "#FFF",
    },
    notesHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 10,
    },
    notesLabel: {
      fontSize: 13,
      fontWeight: "900",
      color: theme.colors.text,
    },
    notesText: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      lineHeight: 22,
      fontWeight: "600",
    },
    ingredientsList: {
      gap: 8,
    },
    ingredientRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 9,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.04)" : "#F7FCF9",
      borderRadius: 14,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    ingredientDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginTop: 7,
    },
    ingredientText: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
    },
    footer: {
      flexDirection: "row",
      padding: 20,
      paddingBottom: 34,
      gap: 12,
      backgroundColor: theme.colors.background,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    editBtn: {
      flex: 1,
      height: 56,
      backgroundColor: theme.colors.card,
      borderRadius: 18,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    editBtnText: {
      fontSize: 16,
      fontWeight: "900",
      color: theme.colors.text,
    },
    usedBtn: {
      flex: 2,
      height: 56,
      backgroundColor: theme.colors.primary,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      elevation: 3,
    },
    usedBtnText: {
      fontSize: 16,
      fontWeight: "900",
      color: "#FFFFFF",
    },
  });
