import { StyleSheet, Dimensions } from "react-native";
import { ThemeType } from "../../constants/theme";

const { width } = Dimensions.get("window");

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    topSection: {
      borderBottomLeftRadius: 36,
      borderBottomRightRadius: 36,
      paddingTop: 58,
      paddingHorizontal: 20,
      paddingBottom: 28,
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.colors.border,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 16,
      zIndex: 10,
    },
    iconButton: {
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 10,
      elevation: isDarkMode ? 0 : 2,
    },
    deleteButton: {
      backgroundColor: isDarkMode ? "#450A0A" : "#FEF2F2",
      marginLeft: 12,
      borderColor: isDarkMode ? "#7F1D1D" : "#FECACA",
    },
    imageContainer: {
      width: "100%",
      height: 340,
      backgroundColor: theme.colors.card,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 2,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: "hidden",
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: isDarkMode ? 0.14 : 0.1,
      shadowRadius: 24,
      elevation: 8,
    },
    heroImage: {
      width: "100%",
      height: "100%",
      borderRadius: 29,
      alignSelf: "center",
    },
    title: {
      fontSize: 28,
      fontWeight: "900",
      color: theme.colors.text,
      marginTop: 18,
      textAlign: "center",
      letterSpacing: -0.4,
    },
    statusBadge: {
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 999,
      marginTop: 10,
    },
    statusText: {
      fontSize: 12,
      fontWeight: "900",
      color: "#FFFFFF",
      letterSpacing: 0.7,
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 18,

    },
    countdownCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 26,
      padding: 18,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 18,
      elevation: isDarkMode ? 0 : 2,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
      marginBottom: 16,
    },
    cardTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flex: 1,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: "800",
      color: theme.colors.text,
    },
    countdownValue: {
      fontSize: 22,
      fontWeight: "900",
      textAlign: "right",
    },
    progressBarBg: {
      height: 10,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.07)" : "#EFF7F2",
      borderRadius: 999,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 999,
    },
    countdownFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      marginTop: 12,
    },
    countdownHint: {
      flex: 1,
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
      lineHeight: 17,
    },
    countdownDate: {
      fontSize: 12,
      fontWeight: "900",
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    gridItem: {
      width: (width - 52) / 2,
      backgroundColor: theme.colors.card,
      borderRadius: 22,
      padding: 15,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: isDarkMode ? 0 : 0.04,
      shadowRadius: 12,
      elevation: isDarkMode ? 0 : 1,
    },
    gridIconBox: {
      width: 38,
      height: 38,
      borderRadius: 14,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "#EFF7F2",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    gridLabel: {
      fontSize: 11,
      color: theme.colors.textSecondary,
      marginBottom: 5,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    gridValue: {
      fontSize: 14,
      fontWeight: "900",
      color: theme.colors.text,
      lineHeight: 18,
    },
    notesCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 18,
      marginTop: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 50
    },
    ingredientsCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 18,
      marginTop: 14,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    notesHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 10,
    },
    notesLabel: {
      fontSize: 13,
      fontWeight: "900",
      color: theme.colors.text,
    },
    notesText: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      lineHeight: 22,
      fontWeight: "600",
    },
    ingredientsList: {
      gap: 8,
    },
    ingredientRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 9,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.04)" : "#F7FCF9",
      borderRadius: 14,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    ingredientDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
      marginTop: 7,
    },
    ingredientText: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
    },
    footer: {
      flexDirection: "row",
      padding: 20,
      paddingBottom: 34,
      gap: 12,
      backgroundColor: theme.colors.background,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    editBtn: {
      flex: 1,
      height: 56,
      backgroundColor: theme.colors.card,
      borderRadius: 18,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    editBtnText: {
      fontSize: 16,
      fontWeight: "900",
      color: theme.colors.text,
    },
    usedBtn: {
      flex: 2,
      height: 56,
      backgroundColor: theme.colors.primary,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
      elevation: 3,
    },
    usedBtnText: {
      fontSize: 16,
      fontWeight: "900",
      color: "#FFFFFF",
    },
  });
