import { StyleSheet } from "react-native";

export const getStyles = (theme: any, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 56,
      paddingBottom: 16,
      gap: 12,
    },
    headerTextWrap: {
      flex: 1,
    },
    headerEyebrow: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      marginBottom: 2,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.05)",
      alignItems: "center",
      justifyContent: "center",
    },
    refreshBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginLeft: "auto",
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.05)",
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.colors.text,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      padding: 20,
      paddingBottom: 40,
    },

    // ── No-household state ──────────────────────────────────────────────
    heroCard: {
      borderRadius: 24,
      padding: 32,
      alignItems: "center",
      marginBottom: 24,
      overflow: "hidden",
    },
    heroBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: isDarkMode ? "rgba(124,58,237,0.16)" : "rgba(124,58,237,0.1)",
      marginBottom: 18,
    },
    heroBadgeText: {
      fontSize: 12,
      fontWeight: "700",
      color: "#7C3AED",
    },
    heroGradientBg: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: isDarkMode ? "#1a1035" : "#f0ebff",
    },
    heroIconContainer: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: isDarkMode ? "rgba(139,92,246,0.25)" : "rgba(139,92,246,0.12)",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 20,
    },
    heroTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: 8,
    },
    heroSubtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      textAlign: "center",
      lineHeight: 22,
    },
    actionCards: {
      gap: 14,
    },
    actionCard: {
      borderRadius: 20,
      padding: 22,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.04)" : "#fff",
    },
    actionIconBox: {
      width: 52,
      height: 52,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    actionContent: {
      flex: 1,
    },
    actionTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: 3,
    },
    actionSubtitle: {
      fontSize: 13,
      color: theme.colors.textSecondary,
    },

    // ── Modal ──────────────────────────────────────────────────────────
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "flex-end",
    },
    modalSheet: {
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      paddingBottom: 32,
      backgroundColor: isDarkMode ? "#1c1c2e" : "#fff",
    },
    modalHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.colors.border,
      alignSelf: "center",
      marginBottom: 24,
    },
    joinModalIconRow: {
      alignItems: "center",
      marginBottom: 16,
    },
    joinModalIconBox: {
      width: 64,
      height: 64,
      borderRadius: 20,
      backgroundColor: isDarkMode ? "rgba(16,185,129,0.15)" : "rgba(16,185,129,0.1)",
      alignItems: "center",
      justifyContent: "center",
    },
    modalSubtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      textAlign: "center",
      marginTop: -12,
      marginBottom: 24,
      lineHeight: 20,
    },
    modalSubtitleLeft: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginTop: -12,
      marginBottom: 24,
      lineHeight: 20,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: theme.colors.text,
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.textSecondary,
      marginBottom: 8,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    textInput: {
      height: 52,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      paddingHorizontal: 16,
      fontSize: 16,
      color: theme.colors.text,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#f8f8fc",
      marginBottom: 20,
    },
    primaryBtn: {
      height: 54,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#7C3AED",
    },
    primaryBtnText: {
      fontSize: 16,
      fontWeight: "700",
      color: "#fff",
    },
    cancelBtn: {
      height: 48,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
    },
    cancelBtnText: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.colors.textSecondary,
    },
    codeInputRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 20,
    },
    codeInput: {
      flex: 1,
      height: 52,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      paddingHorizontal: 16,
      fontSize: 20,
      letterSpacing: 4,
      fontWeight: "700",
      color: theme.colors.text,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#f8f8fc",
      textTransform: "uppercase",
    },

    // ── In-household state ──────────────────────────────────────────────
    householdCard: {
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: isDarkMode ? "rgba(139,92,246,0.3)" : "rgba(139,92,246,0.2)",
      backgroundColor: isDarkMode ? "rgba(139,92,246,0.1)" : "rgba(139,92,246,0.05)",
    },
    householdHeadingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      marginBottom: 18,
    },
    householdAvatar: {
      width: 52,
      height: 52,
      borderRadius: 18,
      backgroundColor: isDarkMode ? "rgba(124,58,237,0.16)" : "rgba(124,58,237,0.12)",
      alignItems: "center",
      justifyContent: "center",
    },
    householdMeta: {
      flex: 1,
    },
    householdName: {
      fontSize: 24,
      fontWeight: "800",
      color: theme.colors.text,
      marginBottom: 4,
    },
    codeSection: {
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.04)",
      borderRadius: 14,
      padding: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    codeLabel: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 4,
    },
    codeValue: {
      fontSize: 24,
      fontWeight: "800",
      letterSpacing: 5,
      color: "#7C3AED",
    },
    copyBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: isDarkMode ? "rgba(124,58,237,0.2)" : "rgba(124,58,237,0.1)",
      alignItems: "center",
      justifyContent: "center",
    },
    shareRow: {
      flexDirection: "row",
      gap: 10,
      marginTop: 14,
    },
    shareBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      height: 46,
      borderRadius: 14,
      backgroundColor: "#7C3AED",
    },
    shareBtnText: {
      fontSize: 14,
      fontWeight: "700",
      color: "#fff",
    },
    copyOutlineBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      height: 46,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: "#7C3AED",
      backgroundColor: isDarkMode ? "rgba(124,58,237,0.08)" : "rgba(124,58,237,0.05)",
    },
    copyOutlineBtnText: {
      fontSize: 14,
      fontWeight: "700",
      color: "#7C3AED",
    },
    sectionLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 14,
    },
    membersCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.03)" : "#fff",
      overflow: "hidden",
      marginBottom: 24,
    },
    memberRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 18,
      paddingVertical: 14,
      gap: 12,
    },
    memberSeparator: {
      height: 1,
      backgroundColor: theme.colors.border,
      marginHorizontal: 18,
    },
    memberAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: isDarkMode ? "rgba(124,58,237,0.25)" : "rgba(124,58,237,0.12)",
      alignItems: "center",
      justifyContent: "center",
    },
    memberAvatarImg: {
      width: 44,
      height: 44,
      borderRadius: 22,
    },
    memberAvatarText: {
      fontSize: 17,
      fontWeight: "700",
      color: "#7C3AED",
    },
    memberInfo: {
      flex: 1,
    },
    memberName: {
      fontSize: 15,
      fontWeight: "600",
      color: theme.colors.text,
    },
    memberRole: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    ownerBadge: {
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: isDarkMode ? "rgba(124,58,237,0.2)" : "rgba(124,58,237,0.1)",
    },
    ownerBadgeText: {
      fontSize: 11,
      fontWeight: "700",
      color: "#7C3AED",
    },
    leaveBtn: {
      height: 54,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: theme.colors.error,
      backgroundColor: isDarkMode ? "rgba(239,68,68,0.08)" : "rgba(239,68,68,0.04)",
    },
    leaveBtnText: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.colors.error,
    },
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
  });
