import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      padding: theme.spacing.lg,
      paddingTop: 60,
      paddingBottom: 120,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    titleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    title: {
      fontSize: 24,
      fontWeight: "900",
      color: theme.colors.text,
    },
    countBadge: {
      minWidth: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.colors.primary + "18",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 8,
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
    },
    countText: {
      fontSize: 12,
      fontWeight: "900",
      color: theme.colors.primary,
    },
    clearButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      backgroundColor: isDarkMode ? "rgba(239, 68, 68, 0.15)" : "#FEF2F2",
      borderWidth: 1,
      borderColor: isDarkMode ? "rgba(239, 68, 68, 0.3)" : "#FEE2E2",
    },
    clearButtonText: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.error,
    },
    inputSection: {
      flexDirection: "row",
      gap: 10,
      marginBottom: theme.spacing.lg,
    },
    inputWrapper: {
      flex: 1,
      height: 52,
      borderRadius: 16,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 16,
      justifyContent: "center",
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.03,
      shadowRadius: 8,
      elevation: isDarkMode ? 0 : 1,
    },
    input: {
      fontSize: 15,
      color: theme.colors.text,
      fontWeight: "600",
    },
    addButton: {
      paddingHorizontal: 20,
      height: 52,
      borderRadius: 16,
      backgroundColor: theme.colors.primary,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    addButtonText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "900",
      letterSpacing: 0.3,
    },
    instructionCard: {
      backgroundColor: theme.colors.card,
      borderRadius: theme.borderRadius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 16,
      marginBottom: theme.spacing.lg,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.02,
      shadowRadius: 8,
      elevation: isDarkMode ? 0 : 1,
    },
    instructionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 8,
    },
    instructionTitle: {
      fontSize: 15,
      fontWeight: "800",
      color: theme.colors.text,
    },
    instructionText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      lineHeight: 18,
      marginBottom: 12,
    },
    stepRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      marginBottom: 8,
    },
    stepNumberContainer: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: theme.colors.primary + "16",
      justifyContent: "center",
      alignItems: "center",
      marginTop: 1,
    },
    stepNumber: {
      fontSize: 11,
      fontWeight: "900",
      color: theme.colors.primary,
    },
    stepText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      flex: 1,
      lineHeight: 18,
    },
    boldText: {
      fontWeight: "800",
      color: theme.colors.text,
    },
    listHeader: {
      fontSize: 14,
      fontWeight: "800",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 10,
      marginTop: 6,
    },
    listContainer: {
      gap: 8,
    },
    completedListHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: theme.spacing.lg,
      marginBottom: 10,
    },
    completedHeaderTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    completedCount: {
      fontSize: 12,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    itemCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 12,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.03,
      shadowRadius: 8,
      elevation: isDarkMode ? 0 : 1,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: theme.colors.textSecondary + "40",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    checkboxChecked: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    productThumbContainer: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: isDarkMode ? "rgba(255, 255, 255, 0.05)" : "#F8FAFC",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    productThumb: {
      width: "100%",
      height: "100%",
      borderRadius: 9,
    },
    productEmoji: {
      fontSize: 20,
    },
    itemInfo: {
      flex: 1,
      minWidth: 0,
    },
    itemName: {
      fontSize: 15,
      fontWeight: "800",
      color: theme.colors.text,
    },
    itemCheckedName: {
      color: theme.colors.textSecondary,
      textDecorationLine: "line-through",
    },
    itemMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 2,
    },
    itemCategory: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.colors.textSecondary,
    },
    itemTag: {
      fontSize: 10,
      fontWeight: "800",
      color: theme.colors.secondary,
      backgroundColor: theme.colors.secondary + "10",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    quantityControls: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F1F5F9",
      borderRadius: 12,
      paddingHorizontal: 4,
      paddingVertical: 4,
      marginRight: 8,
    },
    qtyBtn: {
      width: 28,
      height: 28,
      borderRadius: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    qtyText: {
      fontSize: 13,
      fontWeight: "900",
      color: theme.colors.text,
      paddingHorizontal: 8,
    },
    deleteBtn: {
      padding: 8,
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 30,
      marginTop: 20,
    },
    emptyIconWrap: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 8,
      textAlign: "center",
    },
    emptyText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      textAlign: "center",
      lineHeight: 18,
    },
  });
