import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 40,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 30,
      gap: 16,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    title: {
      fontSize: 24,
      fontWeight: "900",
      color: "#1E293B", // Dark blue from design
    },
    uploadContainer: {
      height: 200,
      borderWidth: 1,
      borderColor: "#CBD5E1",
      borderStyle: "dashed",
      borderRadius: 32,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F8FAFC",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 30,
      overflow: "hidden",
    },
    previewImage: {
      width: "100%",
      height: "100%",
      borderRadius: 32,
    },
    uploadIcon: {
      width: 64,
      height: 64,
      borderRadius: 20,
      backgroundColor: theme.colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    uploadTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#1E293B",
      marginBottom: 4,
    },
    uploadSubtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
    form: {
      gap: 20,
    },
    inputGroup: {
      gap: 8,
    },
    label: {
      fontSize: 15,
      fontWeight: "bold",
      color: "#1E293B",
    },
    inputWrapper: {
      height: 56,
      backgroundColor: isDarkMode ? "#151C2C" : "#F1F5F9",
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: theme.colors.text,
    },
    iconRight: {
      marginLeft: 10,
    },
    colorPickerContainer: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    colorCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: "transparent",
    },
    activeColorCircle: {
      borderColor: theme.colors.primary,
      transform: [{ scale: 1.1 }],
    },
    submitButton: {
      height: 60,
      backgroundColor: "#F1F5F9",
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 30,
    },
    submitButtonText: {
      color: "#64748B",
      fontSize: 17,
      fontWeight: "bold",
    },
    // Add Category Button & Modal
    secondaryButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 10,
      gap: 6,
      marginBottom: 10,
      alignSelf: "flex-start",
    },
    secondaryButtonText: {
      color: theme.colors.primary,
      fontWeight: "bold",
      fontSize: 15,
    },
    categoryModalContainer: {
      width: "100%",
      backgroundColor: isDarkMode ? "#1E293B" : "#FFFFFF",
      borderRadius: 24,
      padding: 24,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 16,
    },
    modalInput: {
      height: 56,
      backgroundColor: isDarkMode ? "#151C2C" : "#F1F5F9",
      borderRadius: 16,
      paddingHorizontal: 16,
      fontSize: 16,
      color: theme.colors.text,
      marginBottom: 20,
    },
    modalActions: {
      flexDirection: "row",
      gap: 12,
    },
    modalButton: {
      flex: 1,
      height: 50,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    modalCancelButton: {
      backgroundColor: isDarkMode ? "#151C2C" : "#F1F5F9",
    },
    modalSaveButton: {
      backgroundColor: theme.colors.primary,
    },
    modalButtonText: {
      fontWeight: "bold",
      fontSize: 16,
    },
    // Animated Dropdown Styles
    dropdownContainer: {
      backgroundColor: isDarkMode ? "#1E293B" : "#FFFFFF",
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: "hidden",
      marginTop: 4,
      position: "absolute",
      top: "100%",
      left: 0,
      right: 0,
      zIndex: 1000,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    dropdownItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    dropdownItemText: {
      fontSize: 16,
      color: theme.colors.text,
    },
    // Calendar & Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    calendarModal: {
      width: "100%",
      maxWidth: 350,
      backgroundColor: "#FFFFFF",
      borderRadius: 24,
      padding: 20,
      elevation: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
    },
    categoryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      justifyContent: "center",
    },
    categoryItem: {
      width: "45%",
      backgroundColor: "#F1F5F9",
      padding: 12,
      borderRadius: 12,
      alignItems: "center",
    },
    // Image Source Modal Styles
    sourceModalContainer: {
      width: "100%",
      backgroundColor: isDarkMode ? "#1E293B" : "#FFFFFF",
      borderRadius: 24,
      padding: 24,
      gap: 16,
    },
    sourceOption: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      backgroundColor: isDarkMode ? "#151C2C" : "#F8FAFC",
      borderRadius: 16,
      gap: 12,
    },
    sourceOptionText: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.text,
    },
    destructiveText: {
      color: "#EF4444",
    },
    // New Styles for Quantity and Notes
    qtyContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 20,
      marginTop: 8,
    },
    qtyButton: {
      width: 48,
      height: 48,
      borderRadius: 14,
      backgroundColor: isDarkMode ? "#151C2C" : "#F1F5F9",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    qtyValue: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.colors.text,
      minWidth: 30,
      textAlign: "center",
    },
    notesInput: {
      height: 120,
      textAlignVertical: "top",
      paddingTop: 16,
    },
  });
