import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      padding: theme.spacing.lg,
      paddingTop: 60,
      paddingBottom: 100,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: theme.spacing.lg,
    },
    greeting: {
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
    appName: {
      fontSize: 28,
      fontWeight: "bold",
      color: theme.colors.primary,
    },
    notificationBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    inventoryBanner: {
      flexDirection: "row",
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      padding: 24,
      marginBottom: theme.spacing.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    inventoryInfo: {
      flex: 1,
    },
    inventoryTitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 4,
      fontWeight: "600",
    },
    inventoryCount: {
      fontSize: 32,
      fontWeight: "900",
      color: theme.colors.text,
    },
    inventoryIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 18,
      backgroundColor: theme.colors.primary + "15", // 15% opacity
      justifyContent: "center",
      alignItems: "center",
    },
    statsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 30,
    },
    statCard: {
      flex: 1,
      borderRadius: 24,
      padding: 16,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "transparent",
    },
    statIconContainer: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: isDarkMode
        ? "rgba(255,255,255,0.08)"
        : "rgba(255,255,255,0.5)",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    statNumber: {
      fontSize: 22,
      fontWeight: "900",
      marginBottom: 2,
    },
    statLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.text,
    },
    sectionTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    seeAll: {
      fontSize: 14,
      color: theme.colors.primary,
      fontWeight: "600",
    },
    expiringList: {
      marginHorizontal: -theme.spacing.lg,
      paddingHorizontal: theme.spacing.lg,
      marginBottom: theme.spacing.xl,
    },
    expiringCard: {
      width: 150,
      backgroundColor: theme.colors.card,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginRight: theme.spacing.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: "center",
    },
    itemIconBg: {
      width: 60,
      height: 60,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    itemName: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.colors.text,
      textAlign: "center",
    },
    itemCategory: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginBottom: theme.spacing.sm,
    },
    daysBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 10,
    },
    daysText: {
      fontSize: 10,
      fontWeight: "700",
    },
    verticalList: {
      gap: theme.spacing.md,
      marginBottom: theme.spacing.xl,
    },
    itemCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      padding: theme.spacing.md,
      borderRadius: theme.borderRadius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    iconBg: {
      width: 50,
      height: 50,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
      marginRight: theme.spacing.md,
    },
    info: {
      flex: 1,
    },
    name: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.text,
    },
    category: {
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: "600",
    },
    // Updated High-Fidelity Notification Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderColor: theme.colors.border,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    markAllText: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.primary,
    },
    sectionHeader: {
      backgroundColor: isDarkMode ? "#25282B" : "#F3F4F6",
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    sectionHeaderText: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.colors.textSecondary,
    },
    notificationItem: {
      flexDirection: "row",
      padding: 20,
      borderBottomWidth: 1,
      borderColor: theme.colors.border,
    },
    unreadItem: {
      backgroundColor: isDarkMode
        ? "rgba(0, 229, 255, 0.05)"
        : "rgba(0, 229, 255, 0.03)",
    },
    notifIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    notifContent: {
      flex: 1,
    },
    notifTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 4,
    },
    notifTitleContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    notifTitle: {
      fontSize: 17,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    notifTime: {
      fontSize: 13,
      color: theme.colors.textSecondary,
    },
    notifDesc: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      lineHeight: 22,
    },
    boldKeyword: {
      fontWeight: "bold",
      color: theme.colors.text,
    },
    errorKeyword: {
      fontWeight: "bold",
      color: theme.colors.error,
    },
    successKeyword: {
      fontWeight: "bold",
      color: theme.colors.primary,
    },
    modalFooter: {
      padding: 20,
      alignItems: "center",
      borderTopWidth: 1,
      borderColor: theme.colors.border,
    },
    footerText: {
      fontSize: 17,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    // Empty State Styles
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
      paddingHorizontal: 40,
    },
    emptyIconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: 10,
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 25,
    },
    emptyButton: {
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 25,
      paddingVertical: 12,
      borderRadius: 25,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    emptyButtonText: {
      color: "#FFF",
      fontWeight: "bold",
      fontSize: 16,
    },
    loadingContainer: {
      paddingVertical: 40,
      alignItems: "center",
      justifyContent: "center",
    },
  });
