import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      padding: theme.spacing.lg,
      paddingTop: 60,
      paddingBottom: 100,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    greeting: {
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
    appName: {
      fontSize: 30,
      fontWeight: "900",
      color: theme.colors.text,
    },
    notificationBtn: {
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 10,
      elevation: isDarkMode ? 0 : 2,
    },
    dashboardHero: {
      backgroundColor: theme.colors.card,
      borderRadius: 30,
      padding: 20,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDarkMode ? 0.12 : 0.07,
      shadowRadius: 24,
      elevation: 4,
    },
    heroTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    heroBadge: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: theme.colors.primary + "12",
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
    },
    heroBadgeText: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: "800",
    },
    heroRefreshButton: {
      width: 36,
      height: 36,
      borderRadius: 14,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "#EFF7F2",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    heroMainRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      marginBottom: 20,
    },
    heroCopy: {
      flex: 1,
    },
    heroLabel: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 4,
    },
    heroTitle: {
      fontSize: 28,
      fontWeight: "900",
      color: theme.colors.text,
      letterSpacing: -0.4,
    },
    heroSubtitle: {
      fontSize: 13,
      lineHeight: 19,
      color: theme.colors.textSecondary,
      marginTop: 6,
      fontWeight: "600",
    },
    heroIcon: {
      width: 62,
      height: 62,
      borderRadius: 22,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.primary + "20",
    },
    heroHealthRow: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 22,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.04)" : "#F7FCF9",
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingVertical: 14,
    },
    heroHealthItem: {
      flex: 1,
      alignItems: "center",
    },
    heroHealthValue: {
      fontSize: 20,
      fontWeight: "900",
      marginBottom: 2,
    },
    heroHealthLabel: {
      fontSize: 11,
      fontWeight: "800",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    heroDivider: {
      width: 1,
      height: 30,
      backgroundColor: theme.colors.border,
    },
    quickActionsRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: theme.spacing.md,
    },
    quickAction: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 18,
      paddingVertical: 12,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0 : 0.04,
      shadowRadius: 10,
      elevation: isDarkMode ? 0 : 1,
    },
    quickActionIcon: {
      width: 30,
      height: 30,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    quickActionText: {
      fontSize: 13,
      fontWeight: "800",
      color: theme.colors.text,
    },
    statsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 10,
      marginBottom: 24,
    },
    statCard: {
      flex: 1,
      borderRadius: 22,
      padding: 14,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.card,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: isDarkMode ? 0 : 0.04,
      shadowRadius: 12,
      elevation: isDarkMode ? 0 : 1,
    },
    statIconContainer: {
      width: 42,
      height: 42,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    statNumber: {
      fontSize: 22,
      fontWeight: "900",
      marginBottom: 2,
    },
    statLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.text,
    },
    sectionTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    sectionTitleCluster: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    sectionCountPill: {
      minWidth: 26,
      height: 26,
      paddingHorizontal: 8,
      borderRadius: 999,
      backgroundColor: theme.colors.primary + "12",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
    },
    sectionCountText: {
      fontSize: 12,
      fontWeight: "900",
      color: theme.colors.primary,
    },
    seeAll: {
      fontSize: 14,
      color: theme.colors.primary,
      fontWeight: "600",
    },
    productFilterRow: {
      gap: 8,
      paddingBottom: 12,
    },
    productFilterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    activeProductFilterChip: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    productFilterText: {
      fontSize: 13,
      fontWeight: "800",
      color: theme.colors.textSecondary,
    },
    activeProductFilterText: {
      color: "#FFFFFF",
    },
    filterCountBadge: {
      minWidth: 22,
      height: 22,
      borderRadius: 999,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "#EFF7F2",
      paddingHorizontal: 6,
    },
    activeFilterCountBadge: {
      backgroundColor: "rgba(255,255,255,0.22)",
    },
    filterCountText: {
      fontSize: 11,
      fontWeight: "900",
      color: theme.colors.textSecondary,
    },
    activeFilterCountText: {
      color: "#FFFFFF",
    },
    expiringList: {
      marginHorizontal: -theme.spacing.lg,
      paddingHorizontal: theme.spacing.lg,
      marginBottom: theme.spacing.xl,
    },
    expiringCard: {
      width: 150,
      backgroundColor: theme.colors.card,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginRight: theme.spacing.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: "center",
    },
    itemIconBg: {
      width: 60,
      height: 60,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    itemName: {
      fontSize: 16,
      fontWeight: "bold",
      color: theme.colors.text,
      textAlign: "center",
    },
    itemCategory: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      marginBottom: theme.spacing.sm,
    },
    daysBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 10,
    },
    daysText: {
      fontSize: 10,
      fontWeight: "700",
    },
    verticalList: {
      gap: 12,
      marginBottom: theme.spacing.xl,
    },
    inlineEmptyState: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 24,
      paddingVertical: 24,
      paddingHorizontal: 18,
      marginBottom: theme.spacing.xl,
    },
    inlineEmptyTitle: {
      fontSize: 15,
      fontWeight: "900",
      color: theme.colors.text,
      marginTop: 8,
      marginBottom: 4,
    },
    inlineEmptyText: {
      fontSize: 12,
      fontWeight: "600",
      color: theme.colors.textSecondary,
      textAlign: "center",
    },
    itemCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      padding: 12,
      paddingLeft: 16,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      position: "relative",
      overflow: "hidden",
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 14,
      elevation: isDarkMode ? 0 : 2,
    },
    recentItemCard: {
      backgroundColor: isDarkMode ? theme.colors.card : "#FEFFFE",
    },
    itemStatusStrip: {
      position: "absolute",
      left: 0,
      top: 14,
      bottom: 14,
      width: 4,
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
    },
    iconBg: {
      width: 58,
      height: 58,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    productThumb: {
      width: "100%",
      height: "100%",
      borderRadius: 17,
    },
    info: {
      flex: 1,
      minWidth: 0,
    },
    productTopRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 8,
    },
    name: {
      fontSize: 16,
      fontWeight: "800",
      color: theme.colors.text,
      flex: 1,
    },
    recentLabel: {
      maxWidth: 86,
      fontSize: 10,
      fontWeight: "800",
      color: theme.colors.primary,
      backgroundColor: theme.colors.primary + "12",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      overflow: "hidden",
    },
    productMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      flexWrap: "wrap",
      marginBottom: 9,
    },
    categoryPill: {
      maxWidth: 100,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "#EFF7F2",
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    category: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
    },
    dateMeta: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    dateMetaText: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
    },
    qtyPill: {
      backgroundColor: theme.colors.primary + "12",
      paddingHorizontal: 7,
      paddingVertical: 4,
      borderRadius: 999,
    },
    qtyPillText: {
      fontSize: 11,
      fontWeight: "900",
      color: theme.colors.primary,
    },
    productProgressTrack: {
      height: 5,
      borderRadius: 999,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.06)" : "#EFF7F2",
      overflow: "hidden",
      marginTop: 1,
    },
    productProgressFill: {
      height: "100%",
      borderRadius: 999,
    },
    rightMeta: {
      alignItems: "flex-end",
      justifyContent: "space-between",
      alignSelf: "stretch",
      marginLeft: 8,
      minWidth: 72,
    },
    badge: {
      paddingHorizontal: 9,
      paddingVertical: 6,
      borderRadius: 999,
      maxWidth: 84,
    },
    badgeText: {
      fontSize: 11,
      fontWeight: "900",
      textAlign: "center",
    },
    rowChevron: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#EFF7F2",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    recentProductsRow: {
      gap: 12,
      paddingBottom: theme.spacing.xl,
      paddingRight: 2,
    },
    recentProductCard: {
      width: 164,
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 12,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDarkMode ? 0 : 0.05,
      shadowRadius: 14,
      elevation: isDarkMode ? 0 : 2,
    },
    recentImageWrap: {
      height: 104,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    recentProductImage: {
      width: "100%",
      height: "100%",
      borderRadius: 19,
    },
    recentStatusDot: {
      position: "absolute",
      top: 10,
      right: 10,
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: theme.colors.card,
    },
    recentCardName: {
      fontSize: 15,
      fontWeight: "900",
      color: theme.colors.text,
      marginBottom: 3,
    },
    recentCardCategory: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.colors.textSecondary,
      marginBottom: 10,
    },
    recentCardFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    recentCardTime: {
      flex: 1,
      fontSize: 10,
      fontWeight: "800",
      color: theme.colors.primary,
    },
    recentExpiryBadge: {
      borderRadius: 999,
      paddingHorizontal: 7,
      paddingVertical: 5,
    },
    recentExpiryText: {
      fontSize: 10,
      fontWeight: "900",
    },
    // Updated High-Fidelity Notification Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderColor: theme.colors.border,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    markAllText: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.colors.primary,
    },
    sectionHeader: {
      backgroundColor: isDarkMode ? "#25282B" : "#EFF7F2",
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    sectionHeaderText: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.colors.textSecondary,
    },
    notificationItem: {
      flexDirection: "row",
      padding: 20,
      borderBottomWidth: 1,
      borderColor: theme.colors.border,
    },
    unreadItem: {
      backgroundColor: isDarkMode
        ? "rgba(0, 229, 255, 0.05)"
        : "rgba(0, 229, 255, 0.03)",
    },
    notifIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    notifContent: {
      flex: 1,
    },
    notifTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 4,
    },
    notifTitleContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    notifTitle: {
      fontSize: 17,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    notifTime: {
      fontSize: 13,
      color: theme.colors.textSecondary,
    },
    notifDesc: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      lineHeight: 22,
    },
    boldKeyword: {
      fontWeight: "bold",
      color: theme.colors.text,
    },
    errorKeyword: {
      fontWeight: "bold",
      color: theme.colors.error,
    },
    successKeyword: {
      fontWeight: "bold",
      color: theme.colors.primary,
    },
    modalFooter: {
      padding: 20,
      alignItems: "center",
      borderTopWidth: 1,
      borderColor: theme.colors.border,
    },
    footerText: {
      fontSize: 17,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    // Empty State Styles
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
      paddingHorizontal: 40,
    },
    emptyIconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: 10,
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 25,
    },
    emptyButton: {
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 25,
      paddingVertical: 12,
      borderRadius: 25,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    emptyButtonText: {
      color: "#FFF",
      fontWeight: "bold",
      fontSize: 16,
    },
    loadingContainer: {
      paddingVertical: 40,
      alignItems: "center",
      justifyContent: "center",
    },
  });
