import { StyleSheet } from "react-native";
import { ThemeType } from "../../constants/theme";

export const getStyles = (theme: ThemeType, isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      paddingBottom: 16,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: theme.colors.card,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    headerText: {
      flex: 1,
    },
    eyebrow: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 3,
    },
    title: {
      fontSize: 23,
      fontWeight: "900",
      color: theme.colors.text,
    },
    content: {
      paddingHorizontal: 20,
      paddingBottom: 46,
    },
    heroPanel: {
      backgroundColor: theme.colors.card,
      borderRadius: 26,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDarkMode ? 0 : 0.06,
      shadowRadius: 18,
      elevation: isDarkMode ? 0 : 3,
    },
    heroIcon: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: theme.colors.primary + "14",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.primary + "20",
    },
    heroTitle: {
      color: theme.colors.text,
      fontSize: 24,
      fontWeight: "900",
      lineHeight: 30,
      marginBottom: 8,
    },
    heroSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 21,
    },
    aiVisual: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 26,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 14,
    },
    receiptMock: {
      flex: 1,
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F8FAFC",
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      minHeight: 136,
    },
    receiptHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 12,
    },
    receiptTitle: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: "900",
    },
    receiptLine: {
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.border,
      marginBottom: 9,
      width: "92%",
    },
    receiptTotalRow: {
      marginTop: "auto",
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      flexDirection: "row",
      justifyContent: "space-between",
    },
    receiptTotal: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: "900",
    },
    aiBridge: {
      width: 54,
      alignItems: "center",
      gap: 9,
    },
    scanBubble: {
      width: 40,
      height: 40,
      borderRadius: 15,
      backgroundColor: theme.colors.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    inventoryMock: {
      flex: 1,
      backgroundColor: theme.colors.primary + "10",
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: theme.colors.primary + "22",
      minHeight: 136,
    },
    inventoryHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 12,
    },
    inventoryTitle: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: "900",
    },
    inventoryRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 9,
    },
    inventoryText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: "800",
    },
    stepsRow: {
      flexDirection: "row",
      gap: 9,
      marginBottom: 22,
    },
    stepPill: {
      flex: 1,
      minHeight: 42,
      borderRadius: 999,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.border,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 6,
    },
    stepText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: "900",
    },
    scanButton: {
      minHeight: 56,
      backgroundColor: theme.colors.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 9,
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderRadius: 18,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: isDarkMode ? 0 : 0.22,
      shadowRadius: 10,
      elevation: isDarkMode ? 0 : 4,
    },
    buttonText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "900",
    },
    previewCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 24,
      overflow: "hidden",
      marginBottom: 24,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    previewImage: {
      width: "100%",
      height: 260,
      resizeMode: "cover",
    },
    retakeButton: {
      padding: 14,
      alignItems: "center",
      backgroundColor: isDarkMode ? "rgba(255,255,255,0.05)" : "#F8FAFC",
    },
    retakeText: {
      color: theme.colors.primary,
      fontWeight: "900",
    },
    loadingBox: {
      padding: 40,
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    loadingText: {
      marginTop: 16,
      color: theme.colors.textSecondary,
      textAlign: "center",
      fontWeight: "700",
    },
    itemsContainer: {
      marginTop: 2,
    },
    resultsHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      gap: 12,
    },
    resultsTitle: {
      fontSize: 19,
      fontWeight: "900",
      color: theme.colors.text,
    },
    resultsSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: "700",
      marginTop: 3,
    },
    addAllButton: {
      backgroundColor: theme.colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      minWidth: 76,
      alignItems: "center",
    },
    addAllText: {
      color: "#FFFFFF",
      fontWeight: "900",
      fontSize: 12,
    },
    itemCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 15,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    itemInfo: {
      flex: 1,
      minWidth: 0,
    },
    itemName: {
      fontSize: 16,
      fontWeight: "900",
      color: theme.colors.text,
      marginBottom: 7,
    },
    itemMeta: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 9,
      gap: 7,
    },
    tag: {
      backgroundColor: theme.colors.primary + "10",
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.primary + "18",
    },
    tagText: {
      fontSize: 12,
      color: theme.colors.primary,
      fontWeight: "900",
    },
    expiryRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    expiryText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      marginLeft: 6,
      fontWeight: "700",
    },
    addButton: {
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: theme.colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 12,
    },
  });
